Repository Ichchhitmd/FurbioWeb, pull requests merged in 2024-10, with the labels that each got.

#1 Add Folders and Blog Models and Controller
  backend/ormconfig.json
  backend/package.json
  backend/src/app.js
  backend/src/models/blogs.models.js
  backend/src/modules/blogs/blogs.controller.js
  backend/src/modules/blogs/blogs.service.js
  backend/src/routes/blogs.routes.js
  package-lock.json
Labels: enhancement

#6 Add Blog, Author and Categories API
  backend/migrations/20241018100000-create-categories.js
  backend/migrations/20241018110517-create-blogs.js
  backend/migrations/20241018113025-create-authors.js
  backend/package.json
  backend/src/app.module.ts
  backend/src/authors/author.controller.spec.ts
  backend/src/authors/author.controller.ts
  backend/src/authors/author.module.ts
  backend/src/authors/author.service.spec.ts
  backend/src/authors/author.service.ts
  backend/src/authors/dto/create-author.dto.ts
  backend/src/blogs/blogs.controller.spec.ts
  backend/src/blogs/blogs.controller.ts
  backend/src/blogs/blogs.module.ts
  backend/src/blogs/blogs.service.spec.ts
  backend/src/blogs/blogs.service.ts
  backend/src/blogs/dto/create-blogs.dto.ts
  backend/src/categories/categories.controller.spec.ts
  backend/src/categories/categories.controller.ts
  backend/src/categories/categories.module.ts
  backend/src/categories/categories.service.spec.ts
  backend/src/categories/categories.service.ts
  backend/src/categories/dto/create-categories.dto.ts
  backend/src/database/models/blogs/author.model.ts
  backend/src/database/models/blogs/blog.model.ts
  backend/src/database/models/blogs/category.model.ts
  backend/src/middleware/multerMiddleware.ts
  backend/src/products/products.controller.ts
  package-lock.json
Labels: enhancement

#10 Add addIcon button in button component
  cms/furbio-cms/src/app/components/common/addIcon.tsx
  cms/furbio-cms/src/app/components/common/button.tsx
Labels: good first issue

#11 Add Blog Form and Category Form
  cms/furbio-cms/package-lock.json
  cms/furbio-cms/package.json
  cms/furbio-cms/src/app/assets/icons/svgIcon.tsx
  cms/furbio-cms/src/app/components/common/button.tsx
  cms/furbio-cms/src/app/components/rare/blogform.tsx
  cms/furbio-cms/src/app/components/rare/categoryForm.tsx
  cms/furbio-cms/src/app/pages/blog/page.tsx
  cms/furbio-cms/src/app/pages/dashboard/page.tsx
Labels: enhancement

#12 Add Api Services and Fetch Wrapper
  cms/furbio-cms/src/app/config/api/apiconfig.ts
  cms/furbio-cms/src/app/config/api/fetchWrapper.ts
  cms/furbio-cms/src/app/config/services/blogs/blogsServices.ts
  cms/furbio-cms/src/app/types/fetchWrapper/fetchWrapperTypes.ts
Labels: enhancement

#13 Product Page
  cms/furbio-cms/src/app/components/common/miniForm.tsx
  cms/furbio-cms/src/app/components/rare/blogform.tsx
  cms/furbio-cms/src/app/components/rare/productform.tsx
  cms/furbio-cms/src/app/page.tsx
  cms/furbio-cms/src/app/pages/blog/page.tsx
  cms/furbio-cms/src/app/pages/dashboard/page.tsx
  cms/furbio-cms/src/app/pages/product/miniForm.tsx
  cms/furbio-cms/src/app/pages/product/productPage.tsx
  package-lock.json
Labels: enhancement

#15 Add Multipart Form Data
  cms/furbio-cms/src/app/config/api/fetchWrapper.ts
Labels: enhancement

#14 Add Author Input Field in Mini Form
  cms/furbio-cms/src/app/components/common/miniForm.tsx
  cms/furbio-cms/src/app/components/rare/blogform.tsx
Labels: enhancement

#16 Import react quill from next dynamic rather than direct importing
  cms/furbio-cms/src/app/components/rare/productform.tsx
Labels: Fix

#17 Add dynamic placeholder and submit button
  cms/furbio-cms/src/app/components/common/miniForm.tsx
  cms/furbio-cms/src/app/config/services/products/productsServices.ts
  cms/furbio-cms/src/app/pages/blog/page.tsx
  cms/furbio-cms/src/app/pages/product/miniForm.tsx
  cms/furbio-cms/src/app/pages/product/productPage.tsx
Labels: enhancement

#18 fix Mini Adder of product page
  cms/furbio-cms/src/app/pages/blog/page.tsx
  cms/furbio-cms/src/app/pages/product/productPage.tsx
Labels: Fix

#20 Add POST and GET Colors
  cms/furbio-cms/src/app/components/rare/productform.tsx
  cms/furbio-cms/src/app/config/api/apiconfig.ts
  cms/furbio-cms/src/app/config/services/products/productsServices.ts
  cms/furbio-cms/src/app/pages/product/productPage.tsx
  cms/furbio-cms/src/app/types/products/productTypes.ts
Labels: enhancement

#22 Add POST and GET Authors
  cms/furbio-cms/src/app/components/common/miniForm.tsx
  cms/furbio-cms/src/app/components/rare/blogform.tsx
  cms/furbio-cms/src/app/config/api/apiEndpoints.ts
  cms/furbio-cms/src/app/config/services/blogs/blogsServices.ts
  cms/furbio-cms/src/app/pages/blog/page.tsx
  cms/furbio-cms/src/app/types/blogs/blogsTypes.ts
Labels: enhancement

#24 blog category API
  backend/migrations/20241018100001-create-authors.js
  cms/furbio-cms/src/app/components/rare/blogform.tsx
  cms/furbio-cms/src/app/config/api/apiEndpoints.ts
  cms/furbio-cms/src/app/config/services/blogs/blogsServices.ts
  cms/furbio-cms/src/app/pages/blog/page.tsx
  cms/furbio-cms/src/app/pages/product/productPage.tsx
  cms/furbio-cms/src/app/types/blogs/blogsTypes.ts
Labels: enhancement

#25 Add optional on value and handle change of description
  cms/furbio-cms/src/app/components/common/miniForm.tsx
Labels: Fix
